# Generated by Django 3.1.5 on 2021-01-28 14:01

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cajero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.CharField(max_length=4, unique=True)),
                ('apellido', models.CharField(max_length=25)),
                ('nombre', models.CharField(max_length=25)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'cajeros',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('estado', model_utils.fields.StatusField(choices=[('confirmado', 'confirmado'), ('cancelado', 'cancelado')], default='confirmado', max_length=100, no_check_for_status=True)),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caja.cajero')),
            ],
            options={
                'db_table': 'lotes',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'sucursales',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('numero_factura', models.CharField(max_length=10)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_vencimiento', models.DateField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caja.empresa')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caja.lote')),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
        migrations.AddField(
            model_name='lote',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caja.sucursal'),
        ),
    ]
