# Generated by Django 3.1.5 on 2021-01-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_vencimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
