# Generated by Django 3.1.5 on 2021-01-28 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_auto_20210128_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='cajero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='caja.cajero'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='caja.sucursal'),
        ),
    ]
