# Generated by Django 3.1.5 on 2021-01-28 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_auto_20210128_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='caja.empresa'),
        ),
    ]
