# Generated by Django 3.1.5 on 2021-01-28 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_auto_20210128_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='estado',
        ),
    ]
