# Generated by Django 3.1.5 on 2021-01-29 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0005_remove_lote_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.CharField(max_length=4, unique=True)),
                ('apellido', models.CharField(max_length=25)),
                ('nombre', models.CharField(max_length=25)),
                ('mail', models.EmailField(max_length=254)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'empleados',
            },
        ),
        migrations.RemoveField(
            model_name='pago',
            name='fecha_vencimiento',
        ),
        migrations.AddField(
            model_name='pago',
            name='codigo',
            field=models.CharField(default='01005198634000311000210197', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('mail', models.EmailField(max_length=255, unique=True, verbose_name='mail')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='caja.empleado')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.AlterField(
            model_name='lote',
            name='cajero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='caja.empleado'),
        ),
        migrations.DeleteModel(
            name='Cajero',
        ),
    ]
