# Generated by Django 3.1.5 on 2021-02-04 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0006_auto_20210129_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='empleado',
        ),
    ]
